# Site settings
name: Zoran
email: zoranzhang@outlook.com
author: 
url: 
resume_site: 
github: https://github.com/zoranzzl
baseurl: 
description: Send me to hell!
meta_description: 咸鱼翻身？不存在的。翻了身的咸鱼不还是咸鱼？
motto: 
banner: 

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: zoranzzl
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

FB:
  comments :
    provider : 
    duoshuo:
        short_name : 
    disqus :
        short_name : 
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light