# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zoran
email: zoranzhang@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  The secret of life is not to do what you love, but to try to enjoy what you have to do.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

github_username:  zoranzzl
email:  zoranzhang@outlook.com
# Build settings
markdown: kramdown
